language: java
sudo: false

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master
  
before_script:
  - sudo apt-get install ant-optional
  
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report